ALTER TABLE odds ALTER COLUMN home_win_odd DROP NOT NULL;
ALTER TABLE odds ALTER COLUMN draw_odd DROP NOT NULL;
ALTER TABLE odds ALTER COLUMN away_win_odd DROP NOT NULL;

ALTER TABLE odds ADD COLUMN market VARCHAR(50);
ALTER TABLE odds ADD COLUMN odds_value NUMERIC(10, 2);
ALTER TABLE odds ADD COLUMN bookmaker_key VARCHAR(50);
